name: frame_forge
description: "A Flutter package for creating dynamic UI layouts with a visual editor. Build and modify app interfaces using drag-and-drop components without code changes."
version: 1.0.0
repository: https://github.com/itjn-ru/frame_forge

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.0
  intl: ^0.20.2
  keymap: ^0.0.92
  file_picker: ^10.3.2
  uuid: ^4.4.0
  vector_math: ^2.1.4
  xml: ^6.5.0
  web: ^1.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Explicitly declare platform support
platforms:
  android:
  ios:
  linux:
  macos:  
  web:
  windows:

flutter:
