name: frame_forge
description: "A DSL Model with UI editor."
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  keymap: ^0.0.92
  file_picker: ^10.3.2
  uuid: ^4.4.0
  vector_math: ^2.1.4
  xml: ^6.5.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
